-- Create items table
CREATE TABLE IF NOT EXISTS public.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  subcategory TEXT,
  size TEXT,
  variant TEXT,
  price NUMERIC NOT NULL,
  "isAvailable" BOOLEAN DEFAULT true NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'Completed' NOT NULL,
  subtotal NUMERIC NOT NULL,
  discount NUMERIC DEFAULT 0,
  "discountPercentage" NUMERIC DEFAULT 0,
  "discountAmount" NUMERIC DEFAULT 0,
  "finalTotal" NUMERIC NOT NULL,
  "paymentMethod" TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create order items table
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  "itemId" BIGINT, -- Null if original item deleted
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  subcategory TEXT,
  price NUMERIC NOT NULL,
  quantity INTEGER NOT NULL,
  notes TEXT,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create settings table
CREATE TABLE IF NOT EXISTS public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shopName" TEXT DEFAULT '67 Café' NOT NULL,
  address TEXT DEFAULT '' NOT NULL,
  phone TEXT DEFAULT '' NOT NULL,
  "footerMessage" TEXT DEFAULT 'Thank you!' NOT NULL,
  "printerType" TEXT DEFAULT 'USB' NOT NULL,
  "printerAddress" TEXT DEFAULT '' NOT NULL
);

-- Insert default settings row
INSERT INTO public.settings (id, "shopName", address, phone, "footerMessage", "printerType", "printerAddress") 
VALUES (1, '67 Café', '', '', 'Thank you!', 'USB', '')
ON CONFLICT (id) DO NOTHING;
